### ISSUE TITLE
callback function for playOnce is called multiple times

### ISSUE THREAD

**Issue by herrKlein** [pixijs/pixi-particles#106]
My callback function is called repeatedly after the first time I called playOnce.

After the emitter has finished update still is called and ```this._completeCallback();``` keeps being called because its not emitting and there are no active particles.

Maybe this._completeCallback should be nullified?

```
		//if we are all done and should destroy ourselves, take care of that
		if (!this._emit && !this._activeParticlesFirst)
		{
			if (this._completeCallback)
			{
				this._completeCallback();
			}
			if (this._destroyWhenComplete)
			{
				this.destroy();
			}
		}
```

**Comment by lePioo** [comment]
Exactly the same here, using PIXI V5

**Comment by andrewstart** [comment]
Yep, the callback should be nulled. It works fine with `playOnceAndDestroy()`, but not `playOnce()`.
