### ISSUE TITLE
Sprite animation

### ISSUE THREAD

**Issue by RodrigoHamuy** [pixijs/pixi-particles#111]
Hi, maybe I am missing something, but I can't get pixi-particles to work with sprite animations?

Code: https://codesandbox.io/s/pixi-particles-animatedsprite-37w0v

Thanks

**Comment by themoonrat** [comment]
https://codesandbox.io/s/pixi-particles-animatedsprite-4d1md

textOptions needed to be an array, and you need to change the particleConstructor on the emitter.

**Comment by RodrigoHamuy** [comment]
Thank you @themoonrat.
