### ISSUE TITLE
Prewarm?

### ISSUE THREAD

**Issue by digilocker** [pixijs/pixi-particles#118]
Hi, sorry if this is already a feature but can't see anything for it..

Is it possible to prewarm the emitters in anyway.  I've been trialing a fog simulation, nothing fancy.  It looks fine when running, but starting up it looks a bit strange until the particles settle into their looping pattern.

In the end this maybe masked anyway with a menu or something but would be great if there was a possible alternative?

Thanks in advance!

**Comment by andrewstart** [comment]
So you just want the emitter to look like it has been running for a while when it is first seen? You'll need to call `myEmitter.update(<seconds to have been running for>);` - You may see a quick hitch in your framerate as many new particles are instantiated, but the emitter should interpolate all the particles that it creates into the appropriate positions (and just skip any that would be spawned and immediately killed, so passing in a number larger than your particle lifetime shouldn't cause any problems).

**Comment by digilocker** [comment]
@andrewstart sorry for the delay in getting back to you.  Had been working on other parts of the project so was awaiting to get back to this.  Just to confirm that solution worked perfectly, many thanks! :)

**Comment by andrewstart** [comment]
You and another person asked in the span of a week, so it sounds like I should document that clearly!

**Comment by teganfleishman** [comment]
Is there a way to accomplish this if `autoUpdate` is `true` for the emitter? An initial call to `update()` seems to be ignored in this case.
