### ISSUE TITLE
Particles dont work in pixi v5

### ISSUE THREAD

**Issue by dr3adx** [pixijs/pixi-particles#120]
**How to reproduce:**
I just took spaceship destructible example and put:

`		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.2.0/pixi.min.js"></script>
		<script src="https://pixijs.io/pixi-particles/dist/pixi-particles.js"></script>
`

And it doesn't work, no errors in console, only framerates showing with white screen, changing it to pixi 4.6.2 works

**Comment by andrewstart** [comment]
The code that runs the examples only works on PIXI 4.X, because the process for creating a new renderer changed in PIXI 5. In the project code, see the `test/` folder to see different configurations of v4 and v5 working with Pixi Particles.

**Comment by dr3adx** [comment]
> The code that runs the examples only works on PIXI 4.X, because the process for creating a new renderer changed in PIXI 5. In the project code, see the `test/` folder to see different configurations of v4 and v5 working with Pixi Particles.

alright thanks
