### ISSUE TITLE
[Request] Compiled and minimized builds

### ISSUE THREAD

**Issue by Article19** [pixijs/pixi-particles#134]
Hi there,

Would it be possible to provide compiled and minimized builds with each release? We're not presently set up for creating these ourselves...

Cheers.

**Comment by andrewstart** [comment]
Install via npm (or yarn, or your choice of any tool that pulls from the npm registry). Inside the `pixi-particles` folder that is downloaded, `dist/pixi-particles.js` will be the library compiled into one file, and `dist/pixi-particles.min.js` will be the minified version of that. Both of the files in the `dist` folder set up a `PIXI.particles` namespace on the window and require the `PIXI` namespace to already exist.

**Comment by Article19** [comment]
Turns out we had a license to CodeKit for OSX, and were able to make a build. Thanks so much!
