### ISSUE TITLE
use ParticleRenderer

### ISSUE THREAD

**Issue by connorjclark** [pixijs/pixi-particles#136]
ParticleContainer would be good for performance. Has there been any discussion about using this?

Or maybe I just need to use a `ParticleContainer` as the `container` input, and that's good enough? Sorry, new to this :)

See:

https://pixijs.download/dev/docs/PIXI.ParticleContainer.html
https://github.com/pixijs/pixi.js/tree/dev/packages/particles

**Comment by andrewstart** [comment]
As you provide the container, all you need to do is provide a ParticleContainer (and configure it for the changes your particles need).

**Comment by connorjclark** [comment]
Cool, thank you for the confirmation.
