### ISSUE TITLE
Wired particle image by ParticleContainer

### ISSUE THREAD

**Issue by SeminYun** [pixijs/pixi-particles#14]
HI. 

Thx for updating new PixiParticle .

particleContainerPerformance can see different screen between  particleContinaer  and normal Container.

it seems because of draw order...

particleContainer draw newPartcile under old Particle.
but Container draw newParticle upper old particle...

so i can see different screen;;

thx.

**Comment by andrewstart** [comment]
It looks like ParticleContainer ignores the blend mode of children and only uses its own blend mode - would this cause the effects you are seeing?
