### ISSUE TITLE
AnimatedParticle makes flickers.

### ISSUE THREAD

**Issue by novogrammer** [pixijs/pixi-particles#150]
Hi, I found this at frame calculation.

```
        {
          framerate: 12,
          loop: true,
          textures: [
            "./assets/img/dummy/bunny.png",
            "./assets/img/dummy/bunny.png", //same image
          ],
        },
```
https://github.com/pixijs/pixi-particles/blob/7d385da292404efb18b0a5d13e6f35ccf06293b5/src/AnimatedParticle.ts#L150-L152
`console.log(frame);` sometimes `frame` eq `2`.

add a follow line to quick fix this issue.
```
            frame = Math.min(frame, this.textures.length - 1);
```

**Comment by andrewstart** [comment]
Would it also fix it to change `if (this.elapsed > this.duration)` -> `if (this.elapsed >= this.duration)` instead?

**Comment by novogrammer** [comment]
> Would it also fix it to change if (this.elapsed > this.duration) -> if (this.elapsed >= this.duration) instead?

No, It was not fixed.

In my case, `emitter.update(1/60);` may cause this.
Rational Number???

Please see my log when `frame` eq `2`.
```
{
    "frame": 2,
    "delta": 0.016666666666666666,
    "elapsed": 0.16666666666666663,
    "duration": 0.16666666666666666
}
```

> Would it also fix it to change if (this.elapsed > this.duration) -> if (this.elapsed >= this.duration) instead?

In case of `emitter.update(1/50);` It was fixed.

**Comment by andrewstart** [comment]
Fixed in version 4.3.1.

**Comment by JPM87** [comment]
Hi,
I am facing the same flickering issue when I am using 2 different textures....

following setup works fine
`textures: [
    "assets/effect-yellow.png",
    "assets/effect-yellow.png",
 ]`

following not:
`textures: [
    "assets/effect-yellow.png",
    "assets/effect-red.png",
 ]`

but when I am using two different textures it all begins starts to flicker.... like sometimes a texture is missing but it is not!

**Comment by andrewstart** [comment]
Are you using a `ParticleContainer` as the parent of your particles?

**Comment by JPM87** [comment]
> Are you using a `ParticleContainer` as the parent of your particles?

Yes, exactly.

**Comment by andrewstart** [comment]
ParticleContainer requires that all children use one BaseTexture (either one Texture, or all Textures from one atlas). Additionally, the intended usage for ParticleContainer isn't the same as how this particle library functions, so you'd probably see better performance with the LinkedListContainer from this library.
