### ISSUE TITLE
Can I use pixi-particles as a mask for a sprite or container?

### ISSUE THREAD

**Issue by jpolitowski** [pixijs/pixi-particles#157]
I'm trying to achieve something like the Pixi.js homepage that has an image masked by what could possibly be a particle system.

I was able to put pixi-particles into a sprite and have that render correctly, but when I set that sprite up as a mask for another sprite, they disappear.

**Comment by andrewstart** [comment]
My understanding of masks is that a single sprite can be a mask (not children of a sprite), and that any sprite or graphics used as a mask will be marked as not renderable (thus disappearing).

**Comment by jpolitowski** [comment]
That makes sense. I'm really curious how the pixi.js homepage effect was created with that animated amoeba like mask. I need to accomplish something similar. Thanks!

**Comment by andrewstart** [comment]
Someone asked about that a few years ago. It is (or was at the time) an
iframe of http://pixijs.teamgbaws.net/header/ which has minified code for
you to look at. I believe it is a custom shader, definitely not pixi
particles.
