### ISSUE TITLE
cannot read `length` of `undefined` in `parseArt`

### ISSUE THREAD

**Issue by hood** [pixijs/pixi-particles#159]
I'm setting up an emitter like:
```
    const e = new Emitter(
      container,
      textures, // <- aray of `PIXI.Texture`s
      config
    );

    e.particleConstructor = AnimatedParticle;
```

And getting the following runtime exception thrown at me:
`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined`

Actual example of usage:
[here](https://imgur.com/a/j85XbVe)

**Comment by andrewstart** [comment]
`AnimatedParticle` doesn't take an array of textures - see the [docs for AnimatedParticle](https://pixijs.io/pixi-particles/docs/classes/animatedparticle.html) on how the art should be formed.

**Comment by hood** [comment]
Oh thanks, I had read that piece of code a trillion times, but I always overlooked the fact that `textures` was a property of an object.
Better typing should be applied to `Emitter` tho.
