### ISSUE TITLE
Add "middle" option for alpha, scale and color properties

### ISSUE THREAD

**Issue by alexandervrs** [pixijs/pixi-particles#20]
Having a middle value for alpha and scale would be very useful. For example, I might need to first fade in a particle, then fade it out. So I'd do:

```
    "alpha": {
        "start": 0.0,
        "middle": 1.0,
        "end": 0.0
    }
```

Currently this does not seem possible with this engine.
Hence, I propose an optional "middle" property for alpha, scale and color.
Being optional meaning that the property could be omitted and the emitter work as it does now.

**Comment by andrewstart** [comment]
Something like this is definitely something I'd like to do.

**Comment by Rollo-Liu** [comment]
This thing cloud be very nice. At the moment I have to add an tween animation for the alpha value of the particle container (as a quick solution).

**Comment by bQvle** [comment]
Hi Andrew, hope you're doing well!

I've been missing this feature aswell,

The middle value should have a position parameter. 
"middle": [1.0, 0.1] 
which would indicate that the middle value is reached at 10% of the lifetime.

also it should not be required.

**Comment by andrewstart** [comment]
Yeah, I definitely want to figure out a clean and understandable way to have this happen. I'd like to allow for an arbitrary number of points, rather than just 'middle'.

**Comment by bQvle** [comment]
that would be the best solution yes, maybe change it to arrays
"alpha": [
     0,
     1,
     0.5,
     0
]

by default it could devide the lifetime over all the points, and if you want control over the timings you could pass them as arrays

"alpha": [
     [0, 0],
     [1, 0.1],
     [0.5, 0.9],
     [0, 1]
]

**Comment by funkypaul** [comment]
+1 for this feature!

**Comment by johanlajili** [comment]
+10 for this feature. It's really missed. Look at how it's done on different engines for inspiration (CSS transitions, Unity...).

Myself I would go for:

```
alpha: {
"start" : 0,
"10%": 0.5,
"50%": 1,
"100%": 0
}
```
This way:
it's retro compatible with the current version ("start" and "0%" are equivalent, so are "end" end "100%". You could also add middle in there).
It give you enough granularity, but you can just use keyword if you don't want it.

**Comment by andrewstart** [comment]
Besides just generally being busy, I've been holding off on this because I haven't been looking forward to doing the editor portion of this, which will be a bit of an ordeal, I'm sure.

However, if you want to be on the cutting edge, I've started working on the runtime half in [this branch](https://github.com/pixijs/pixi-particles/tree/value-lists). The `alpha`, `color`, `scale`, and `speed` properties can be set up in a list in the JSON config as such: (replacing the old `{start, end}` format)
```json
{
    "alpha": {
        "list": [
            {"value":1, "time":0},
            {"value":0.5, "time":0.25},
            {"value":0, "time":1}
        ],
        "isStepped":false
    },
    "color": {
        "list": [
            {"value":"00FF00", "time":0},
            {"value":"FF0000", "time":0.5},
            {"value":"0000FF", "time":1}
        ],
        "isStepped":false
    }
}
```
I have not actually tested the new config format yet, just confirmed that I am properly converting the old format into the new code.

**Comment by AndyNormore** [comment]
+1 Very cool!

**Comment by stephanedemotte** [comment]
+1 ! neeeed !

**Comment by andrewstart** [comment]
Added in [version 3](https://github.com/pixijs/pixi-particles/releases/tag/3.0.0) (no editor support yet)
