### ISSUE TITLE
PIXI.particles namespace collision in v4

### ISSUE THREAD

**Issue by AMorporkian** [pixijs/pixi-particles#23]
In Pixi v4, currently in rc1, PIXI has created its own PIXI.particles namespace. This module, in conjunction with PIXI v4, overwrites all of the necessary stuff you need in there.

I would recommend checking if PIXI.particles already exists, and if it does, simply merge your keys in with it instead of overwriting it entirely.

**Comment by andrewstart** [comment]
That is an excellent point/suggestion, and has been taken care of with version 1.6.4.

**Comment by AMorporkian** [comment]
You're awesome. Thanks!
