### ISSUE TITLE
Use PIXI.particles.ParticleContainer when it exists

### ISSUE THREAD

**Issue by AMorporkian** [pixijs/pixi-particles#24]
Following hot on the heels of #23, using PIXI.ParticleContainer throws a deprecation warning. Changing both instances of `ParticleContainer = PIXI.ParticleContainer` to `ParticleContainer = PIXI.particles.ParticleContainer || PIXI.ParticleContainer` should resolve the issue an retain backwards compatibility.

I was getting a PR ready, but I noticed you have no dev dependencies nor a build process defined.

**Comment by andrewstart** [comment]
You know, I thought about this before, but forgot when I actually fixed the namespacing. Fixed in version 1.6.5.
We actually have some Grunt stuff in the dev dependencies, although I don't know if that is going to be changed in the near future or not.
