### ISSUE TITLE
setTexture() throws in console

### ISSUE THREAD

**Issue by Oza94** [pixijs/pixi-particles#25]
Hello,

When updating pixi.js to 3.0.10, pixi-particles throws deprecation warnings in the console `setTexture() is deprecated, use sprite.texture = texture`. Updating pixi-particles to 1.6.5 did not change anything.

I can easily fix that and PR but I also noticed you are working on v4 compatibility. Is it still relevant to make a PR in the coming days for that ?

Awesome job by the way, I love this lib !

**Comment by andrewstart** [comment]
The library should be detecting Pixi v3+ and using the `texture` setter. Did something happen with 3.0.10 to make `PIXI.VERSION` not exist or be an invalid value?

**Comment by Oza94** [comment]
Hum probably! Look at this from my console : 

![Screenshot](http://i.imgur.com/s6r6D1S.png)

I'll ask on pixi.js repo about this.

**Comment by Oza94** [comment]
Closing in favor of pixi.js issue. Thanks !
