### ISSUE TITLE
Random particle velocity without rotation

### ISSUE THREAD

**Issue by bigbadwofl** [pixijs/pixi-particles#28]
I'd love to be able to specify the range of directions particles should move (startRotation) without actually having the particles rotate themselves. I'm working on a low-fi roguelike mmo and rotated particles don't really fit in aesthetically. I'll hack it in for now but if it's something you feel would be useful, a config option would be really nice.

**Comment by andrewstart** [comment]
Definitely a useful thing, and easy to add. Use version 1.6.8. The editor needs some updates, so in the future the option will be available within that as well.

**Comment by andrewstart** [comment]
The online editor now allows you to edit this option.
