### ISSUE TITLE
Particle spawn chance

### ISSUE THREAD

**Issue by bigbadwofl** [pixijs/pixi-particles#29]
Having a particle emit frequency is great for most cases, but I'd also like to be able to say: each update the chance for a particle to spawn is x. Along with that, specifying the amount of rolls would also help greatly. That is: in this update, roll 5 times and each one under 0.2 (for instance) spawns a particle.

This will allow for some more interesting effects to be obtained, I believe.

**Comment by andrewstart** [comment]
Added in [version 3](https://github.com/pixijs/pixi-particles/releases/tag/3.0.0)
