### ISSUE TITLE
Max Velocity

### ISSUE THREAD

**Issue by PSeitz** [pixijs/pixi-particles#33]
Being able to set max velocity, to avoid endless acceleration would be nice

**Comment by andrewstart** [comment]
That is certainly something that could be added. That said, how long are you keeping your particles around that endless acceleration becomes an issue?

**Comment by PSeitz** [comment]
I guess in my case i starts to look a bit weird after a value of 1.5

**Comment by andrewstart** [comment]
Added in release 1.7.0.
