### ISSUE TITLE
Missing packages from package.json

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi-particles#39]
Hey

When I cloned the repo and installed everything, everytime I tried to do a build it would give me errors about missing packages. As a hack, I dumped everything it mentioned into the package.json itself, versionless, and the builds then worked!

Here's what I dumped in

> "grunt-bower-install-simple": "",
> "grunt-simple-version": "",
> "grunt-text-replace": "",
> "grunt-contrib-clean": "",
> "grunt-contrib-concat": "",
> "grunt-contrib-connect": "",
> "grunt-contrib-jshint": "",
> "grunt-contrib-less": "",
> "grunt-contrib-qunit": "",
> "grunt-contrib-uglify": "",
> "grunt-contrib-watch": "",
> "grunt-contrib-yuidoc": "",
> "grunt-gh-pages": ""

**Comment by andrewstart** [comment]
Hmm, that sounds like a bunch of things that `library-grunt` should be pulling in. Which version of NPM are you using?

**Comment by themoonrat** [comment]
Using node 6.9.1 with npm 3.10.9

**Comment by andrewstart** [comment]
I'll update my node/npm and see if I can figure out why dependencies aren't getting installed then.

**Comment by andrewstart** [comment]
Those dependencies are getting installed normally, but a dependency (a couple layers in) of library-grunt is rather old and doesn't work with npm 3's flat structure. Adding dependencies to this project caused different versions to be fetched for this project vs library-grunt, so library-grunt got its own copies in the same location that they would have been for npm 2.
I think the best solution would be to swap out the build system for pixify, and for the time being your workaround is good enough.

**Comment by andrewstart** [comment]
I've converted the build process, so this should be solved (and the docs match Pixi's!)
