### ISSUE TITLE
Performance on mobile for non white colors (!0XFFFFFF)

### ISSUE THREAD

**Issue by amrelhady** [pixijs/pixi-particles#40]
Thank you very much for all your work on this. It's really awesome. Apologies for the long explanation of the issue but i I tried to include as much details as I can.

I am working on a game and making use of PIXI and PIXI-Particles. It will be a mobile/tablet game wrapped in either Cordova/Crosswalk or Cocoon. At the moment I am using Cocoon's Canvas+(with screencanvas enabled). I am using PIXI-Particles to create an explosion animation.

The issue I have is the initial time it takes for PIXI-Particles emitter to work smoothly. The first time the emitter runs (the first explosion) it causes a massive frame-drop and the animation is laggy and slow. This gets better with the next run of the emitter, but still some lagging. After a few runs it works smoothly. Having said that, occasionally while playing the game the emitter animation(explosion) gets laggy.

I noticed that the emitter works well if the start/end color is set to "0xFFFFFF". Any other color(s) causes big lags on initial runs.

I had a look at the code for both PIXI and Particles. This is what I've found.

This removes endColor if it's the same as startColor.
https://github.com/pixijs/pixi-particles/blob/master/src/Emitter.js#L536
```
//if it's just one color, only use the start color
if (config.color.start != config.color.end)
{
  this.endColor = ParticleUtils.hexToRGB(config.color.end);
}
else
  this.endColor = null;
```

This prevents any color tinting operation if `endColor` is not set.
https://github.com/pixijs/pixi-particles/blob/master/src/Particle.js#L274
```
this._doColor = !!this.endColor;
```
And https://github.com/pixijs/pixi-particles/blob/master/src/Particle.js#L381
```
if (this._doColor)
	{
		var r = (this._eR - this._sR) * lerp + this._sR;
		var g = (this._eG - this._sG) * lerp + this._sG;
		var b = (this._eB - this._sB) * lerp + this._sB;
		this.tint = ParticleUtils.combineRGBComponents(r, g, b);
	}	
```

And when the particle Sprite is created, it's tint value is set to the startColor:
https://github.com/pixijs/pixi-particles/blob/master/src/Particle.js#L281
```
this.tint = ParticleUtils.combineRGBComponents(this._sR, this._sG, this._sB);
```

The sprite itself initially have a tint of 0xFFFFFF.
https://github.com/pixijs/pixi.js/blob/master/src/core/sprites/Sprite.js#L75
```
this.tint = 0xFFFFFF;
```

When the sprite is rendered, a tint is applied IF the Sprite object's `tint` IS NOT 0XFFFFFF:
https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/canvas/CanvasSpriteRenderer.js#L127
```
if (sprite.tint !== 0xFFFFFF)
            {
                 if (sprite.cachedTint !== sprite.tint)
                {
                    sprite.cachedTint = sprite.tint;
                    sprite.tintedTexture = CanvasTinter.getTintedTexture(sprite, sprite.tint);
                }
.
.
.
```

And the tinted Sprite is cached to speed things up.
https://github.com/pixijs/pixi.js/blob/dev/src/core/sprites/canvas/CanvasTinter.js#L28
```
        if (texture.tintCache[stringColor])
        {
            return texture.tintCache[stringColor];
        }
```

Now I am not actually sure if this is possible, but is there a way of setting the initial Particles' sprite texture color/fillColor to anything but 0XFFFFFF? This way, the initial tinting at **CanvasSpriteRenderer.js#L127** can be avoided and would massively improve the animation speed on first runs of the emitter.

Obviously this would only be useful if the start/end colors are the same. Otherwise tinting is required to transition a particle from one color to the other.

Is this feasible? It seems to me that the ```baseTexture.source``` needs to be set somehow but I couldn't figure it out.

**Comment by amrelhady** [comment]
Thanks for your reply themoonrat. I am actually not concerned about tinting from one startColor to endColor, because I know that this requires going through intermediate colors, creating textures, and so on.

I basically trying to find a way to not have the "0XFFFFFF" hard coded, since this seems to be the default color and no tinting takes place in this case.

I could potentially be supplying a texture when calling the constructor here:
https://github.com/pixijs/pixi-particles/blob/master/src/Particle.js#L20
```
var Particle = function(emitter)
	{
		//start off the sprite with a blank texture, since we are going to replace it
		//later when the particle is initialized. Pixi v2 requires a texture, v3 supplies a
		//blank texture for us.
		Sprite.call(this);
```

But I would need to test this, and PIXI itself would then have to NOT assume that initial color of the sprite is 0xFFFFFF.

FYI I am actually warming up the cache now, I have a load screen and I just run the emitter a few times! It works but it's slowing down the game start considerably. On an old Android device it even took 15 seconds. (I hide the load screen after a certain number of frames is rendered.)

**Comment by andrewstart** [comment]
I'm confused as to how setting the initial color is something other than 0xFFFFFF would help - if a particle color is 0xFF0000, the texture should only be tinted once, when the first particle is rendered, and after that all the other particles should share the tinted texture. Besides the cost of creating that tinted texture, it could be that instantiating particles for the first time is too expensive on the old mobile device. To fix that, I'd create a second emitter config for use when you have to fall back to the canvas renderer.

This did make me think that a useful feature would be supplying an array of colors instead of the start/end, and cycling through only those colors. It would be useful for people that want to restrict their game to a specific color palette, but more importantly allow a lighter form of color interpolation for canvas rendering.

**Comment by amrelhady** [comment]
Thanks @andrewstart, apologies for late reply. I am not sure I follow regarding your "second emitter" solution? Do you mean create an emitter with only "0XFFFFFF" start/end colors for use on old/non-webgl devices?

I think I found a solution that would work if you want to only restrict your emitter to one color. Basically use a non-white `particle.png`. I updated the one I am using to yellow instead of white, and I get yellow explosions without tinting. However, I still need to pass "0XFFFFFF" for start/end color to trick emitter/pixi to think no tinting is needed. That is
```
{
   color: {
                start: '0xFFFFFF',
                end:   '0xFFFFFF' // that's not even needed.
   }
}
```
Very good idea about restricting tinting to a list of colors.
