### ISSUE TITLE
Best practices for working with multiple emitters?

### ISSUE THREAD

**Issue by mspanish** [pixijs/pixi-particles#47]
Sorry to be such a noob at this, but as I've never worked with particles before this is all new to me! I've got 3 or 4 cool effects I'm using - 3 are burst type things that only run once when something happens, and 1 is an ongoing bubble generator that runs all of the time.

Do I need to do something to clean up the "run once" emitters? Is it ok to just keep creating them over and over again, or should I create them all in the beginning, and then start and stop them?

thanks in advance for any advice!

**Comment by andrewstart** [comment]
Because the emitters reuse their particles, it is better to keep the "run once" emitters for the next time you need them. When you no longer need them, you should call their `destroy()` method to make sure that they and all their particles get garbage collected.

**Comment by mspanish** [comment]
Thank you, that is really helpful.
