### ISSUE TITLE
Incorrect behavior of  AnimatedParticle.parseArt

### ISSUE THREAD

**Issue by qwertykg** [pixijs/pixi-particles#51]
what it was:

on line 176 : 
for(i = 0; i < art.length; ++i)
        {
            data = art[i];
            art[i] = output = {};
            output.textures = outTextures = [];
            textures = data.textures;
            for(j = 0; j < textures.length; ++j)
            {
              
                tex = textures[j];

what it should be:

  for(i = 0; i < art.length; ++i)
        {
            data = art[i];
            art[i] = output = {};
            output.textures = outTextures = [];
            textures = art;
            for(j = 0; j < textures.length; ++j)
            {

                tex = textures[j];

Because data.textures doesnt return an array, hence textures.length will throw an error

**Comment by andrewstart** [comment]
`data.textures` should be an array, according to the documentation for the class. What are you passing in?

**Comment by qwertykg** [comment]
Was passing in an incorrect config! Works fine now!
