### ISSUE TITLE
Problem with blend mode add

### ISSUE THREAD

**Issue by klaun76** [pixijs/pixi-particles#52]
Hi

We're using pixi particles a lot and we're quite happy with such features in our games. For designing particles we've been using pixi particles editor but our graphic artist needed upgrade. So i decided to to create new editor. (Just putting together angular, bootstrap, pixi and pixi particles. I have only basic knowledge about all modules that i used. Ok, maybe pixi, and pixi particles a little deeper).

I've run to a problem:
I have tested same emitter and image in both particle editors, [mine](ke.sowhat.sk/files/ig2g/particles-editor) and yours. 

But result is different. problem is when blend mode add is set. Could you please give me a hint what has changed in particles, or even pixi? I'm googling around and asking around for a while and cannot find a solution

I'm attaching image and emitter to post
[Archive.zip](https://github.com/pixijs/pixi-particles/files/1018444/Archive.zip)

When webgl renderer is used particles are different. In new editor is much brighter. In canvas result is the same.

Thank you for your cooperation

.mrtn

**Comment by andrewstart** [comment]
Hmm, I haven't tested the blend modes since PIXI 3, it's possible something changed. At the time, I did notice that the blending can look odd if you have a transparent canvas with no background within the stage to be blended into. Could you provide a few screenshots of what is going on? Also, the link to your particle editor is broken.

**Comment by klaun76** [comment]
oh sorry, i did not check how links here work, so link should be external ke.sowhat.sk/files/ig2g/particles-editor
[Archive 2.zip](https://github.com/pixijs/pixi-particles/files/1018679/Archive.2.zip)

cheers
.mrtn

**Comment by klaun76** [comment]
i just found out that there is difference between pixi 3.0.9 and 3.0.10. I switched pixi in my version of particles editor to 3.0.9 and got same results as your particles. Then i looked around in pixi repo and found out that WebGLRenderer.js was changed between versions. (commit 0ccef7a).
So after more than year case closed :-)
I'll probably dig around a little bit more

**Comment by andrewstart** [comment]
To assist your  investigation, the relevant changelog is probably "BlendModes tweaked in webGL to work with pre-multiplied alpha sprites." I don't know exactly what changed there, but that is probably the difference.

**Comment by klaun76** [comment]
I'm already using hotfix like this:
renderer.state.blendModes[PIXI.BLEND_MODES.ADD] [renderer.gl.SRC_ALPHA, renderer.gl.DST_ALPHA] for older games produced in pixi3. 
Dirty solution, but good enough for me :-S
