### ISSUE TITLE
Spawn Type is it able to replace with a new type?

### ISSUE THREAD

**Issue by darting** [pixijs/pixi-particles#54]
Spawn Type is it able to replace with a new type?

such as 
```js
var emitter = new PIXI.particles.Emitter();
emitter.spawner = ringSpawner;
emitter.spawner = pointSpawner;
```

**Comment by andrewstart** [comment]
It is suggested that you don't change the spawn type except by changing the config with `init()`, as each spawn type has its own parameters needed to function correctly. If you are sure that you want to risk changing the spawn type manually, you'd have to look at the code, as the Emitter handles each spawn type with private properties/methods.
