### ISSUE TITLE
Modify Properties of an Existing Emitter

### ISSUE THREAD

**Issue by AndyNormore** [pixijs/pixi-particles#57]
Hi, need to change properties such as lifespan.

If an object moves away from another object, I need the lifespan to be equal to their distance.

So, 

emitter.lifespan(this.x - that.x);

How does one achieve this?

**Comment by andrewstart** [comment]
You can set the `minLifetime` and `maxLifetime` properties on your Emitter. Note that this won't affect particles that have already been spawned.

**Comment by AndyNormore** [comment]
Thanks for the reply. It's fine it wont affect existing particles, that's kind of the point right? :)

Are ALL emitter properties available to be modified? 

I also need to adjust the scale of the particles, as the user zooms out, the scale stays the same and looks weird.

www.StarCommanderOnline.com if you're wanting to have a peek!

**Comment by andrewstart** [comment]
Any public Emitter property not marked as read only can be modified, and will take effect as it continues to spawn more particles.

**Comment by AndyNormore** [comment]
COOL. So something like this?

emitter_warp.speed = 100;
emitter_warp.pos.x = 20;

I'm not having luck with that, is my syntax off?

**Comment by andrewstart** [comment]
Speed is a value interpolated over a particle's lifetime, so the Emitter has `startSpeed` and `endSpeed` properties. For the emitter position, see [`updateSpawnPos()`](http://pixijs.github.io/pixi-particles/docs/PIXI.particles.Emitter.html#updateSpawnPos).

**Comment by AndyNormore** [comment]
Okay great, got what I needed done, done. Thank you!

![image](https://user-images.githubusercontent.com/1661561/27971564-27b0ca22-6321-11e7-8104-59e4757a051e.png)
