### ISSUE TITLE
Question: How to put a container "on top of a bitmap"

### ISSUE THREAD

**Issue by mirraj2** [pixijs/pixi-particles#59]
The documentation says for PIXI.particles.Emitter says the following:

  // The PIXI.Container to put the emitter in
  // if using blend modes, it's important to put this
  // on top of a bitmap, and not use the root stage Container

I am using blendmodes, and things look great when the world is black, but when the particles render over brightly colored terrain, it looks awful.  I understand the need to render the particles onto a separate bitmap and then render that bitmap onto the scene, but I'm unsure of how to do this.

Container has a "cacheAsBitmap", but that just takes a snapshot at a single instance in time.

I also tried passing in a RenderTexture to PIXI.particles.Emitter to no avail.  It fails when trying to add children to the RenderTexture.

How do I back a Container by a bitmap?

**Comment by andrewstart** [comment]
Ah, by this I meant just rendering your particles over other content - I found that it blended oddly (perhaps only for transparent canvases?) when there was no other content behind the particles. The particle editor background color is actually a tinted 10px texture in a Sprite stretched to fill the area.

**Comment by mirraj2** [comment]
I see what you meant by the comment now.  Do you know of a good way of doing an "add" or "screen" blend mode when the background is a bright color?  I want the particles to only blend with each other, not the rest of the scene.

**Comment by andrewstart** [comment]
I think the only option there is to have an off stage container for the particles that is rendered to a RenderTexture, and then use a Sprite to display that RenderTexture in your game world.
