### ISSUE TITLE
Display 3 Different types of  Particles coming from same emitter at once

### ISSUE THREAD

**Issue by sai-sruthi** [pixijs/pixi-particles#60]
Hello,
I have just started coding games please help in the following context. I want the emitter to emit 3 different types of particles the Documentation says use Texture Array, by doing so they only get emitted one after the other and not all mixed together. Can you suggest me a way?

**Comment by andrewstart** [comment]
When you use an array of textures, for each particle emitted the Emitter will randomly pick one of those textures to use for just that particle. If you want 3 separate textures to be used but only one texture at a time for a while, I would suggest using 3 different emitters, or reusing one emitter and changing out the texture on the emitter when it is time to switch.

**Comment by sai-sruthi** [comment]
Hey, Thank for the reply I want to emit mixture of particles, that is I want to see all three particles in the particle emission but adding the Array of Texture also is giving me only individual effect.

**Comment by andrewstart** [comment]
I'm having trouble picturing what your goal is. Could you provide an example of what it looks like right now and explain how that is different from what you want it to do?

**Comment by sai-sruthi** [comment]
Hi, 
I would like to see 2 or 3 different kinds of particles being emitted at the same time. The addition of 2 emitters in the container or addition of 2 particle image textures in the same emitter is giving me the same effect, i.e. they both show only one particle emission after another or they keep swapping emission of particles like particle 1 emits for 1 sec then particle 2 n then particle 3 but not all 3 together continuously which I wanted.

**Comment by andrewstart** [comment]
In the [flame example](http://pixijs.github.io/pixi-particles/examples/flame.html) there is one emitter with an array of 2 images. It emits a mix of the two images continuously.
