### ISSUE TITLE
Are the images in the source free to use?

### ISSUE THREAD

**Issue by issy123** [pixijs/pixi-particles#61]
Are the images in the source free to use?

**Comment by andrewstart** [comment]
`smokeparticle.png` comes from https://github.com/stemkoski/stemkoski.github.com/tree/master/Three.js/images - at the time I added it, I was pretty confident that it was okay to use, although I don't see any license right now so you'd have to ask him to confirm it.
The images in `gold_anim.png` are from some open source license, but I need to do more digging to find where I got them to know the exact license.
Everything else was created by us and is definitely free to use.

**Comment by issy123** [comment]
[The gold anim is from kenney.nl ](http://kenney.nl/assets/jumper-pack)

I will ask for the smokeparticle.
Other things are free to use that's really awesome!
You guys are great! I hope I can share my game once it's finished

**Comment by issy123** [comment]
Can in the editor also an example js file be added with the required images and the config?
Because for every default emitter in the editor i'm missing the images

**Comment by andrewstart** [comment]
Every default emitter is also an [example](https://github.com/pixijs/pixi-particles/tree/master/docs/examples), with the config and names of images used in the .html file.

**Comment by issy123** [comment]
I can't find the trail one, but thanks!

**Comment by andrewstart** [comment]
Also, in the editor if you mouse over the images used in the current particle system, there is a button that is shown to download that image.
