### ISSUE TITLE
How do I get rotating circles rotating around a bigger circle?

### ISSUE THREAD

**Issue by issy123** [pixijs/pixi-particles#62]
[This is what i'm looking for](http://orig13.deviantart.net/969d/f/2011/216/1/7/24_spinning_circles_by_10binary-d45grfs.gif) without the middle one.

In the [pixi particles editor](http://pixijs.github.io/pixi-particles-editor/#) I can select the trail default emitter. The trail default emitter leaves a small trail behind, i want that same effect but also have multiple of those rotate in a circle as seen in the image

**Comment by andrewstart** [comment]
You'd probably be best served by having a set of identical emitters and moving them around in a circle. With this library there is not currently a good way to have a series of trails rotating around a single point with just one emitter.

**Comment by issy123** [comment]
okay cool, thank you for your time
