### ISSUE TITLE
Particles do not get removed from ParticleContainers when they are killed

### ISSUE THREAD

**Issue by jmlee2k** [pixijs/pixi-particles#63]
This is more of a question than an issue.

Looking at the pixi-particles code, I can see that when using a ParticleContainer, instead of removing dead particles from the container, it sets their alpha to 0 and visible to false.

Just curious, is this some sort of performance tweak?  Right now we have a particle system in a ParticleContainer which was created like so:

`				const pContainer = new PIXI.particles.ParticleContainer(1000,{position:true,rotation:true});`

But without passing `alpha:true` to the ParticleContainer constructor, the particles stay on the screen after they are killed.  We're not using alpha in our emitter, so I didn't think we needed to let the ParticleContainer know that that alpha is changing, which is how I came upon this issue.

I'm fine with passing `alpha:true`, I'm just curious about the reasoning behind it, as it seems like it would be a waste of resources to leave particles on the screen.

**Comment by andrewstart** [comment]
It is indeed a performance tweak - ParticleContainers don't seem to like having children constantly added/removed, so my changing particle alpha was a bit of a hack to improve performance (pretty well). However, that was in PIXI 3, and in PIXI 4 the performance does not seem to be nearly as good - I haven't been able to look into what changed with the ParticleContainer, and what the best way to get high performance out of them is.

**Comment by jmlee2k** [comment]
Ok, thanks for the explanation.  We'll just pass alpha:true for now.
