### ISSUE TITLE
[request] Callback on emit complete.

### ISSUE THREAD

**Issue by Rojoss** [pixijs/pixi-particles#67]
Hello, would it be possible to add an callback when the emission has completed?
So basically when the lifetime of the emitter has ended.
I would like to do cleanup of stuff when I have emitters that only play once.
Just destroying the emitter is not enough for me.
Currently I have to set a timeout for the lifetime of the emitter to do the cleanup but I assume that you know in the emitter when it is done emitting since you also added `playOnceAndDestroy`.

**Comment by andrewstart** [comment]
Added in [version 2.1.8](https://github.com/pixijs/pixi-particles/releases/tag/2.1.8)

**Comment by Rojoss** [comment]
Sweet, thanks a lot! 👍
