### ISSUE TITLE
spawnType: Burst not creating particles

### ISSUE THREAD

**Issue by TheBoat** [pixijs/pixi-particles#70]
Hi,

I am trying to use the example from the docs, and it works fine with the spawnType: Circle, but if I change the spawn type to Burst and leave everything else as it is, nothing happens.
Am I missing some additional settings I need to do for burst?

**Comment by andrewstart** [comment]
The burst spawn type expects a `spawnBurst` property with burst specific properties - I recommend using [the editor](http://pixijs.io/pixi-particles-editor/) which will create the required things. You can upload your existing JSON to the editor to use it as a starting point.

**Comment by TheBoat** [comment]
Sweet, thanks!
