### ISSUE TITLE
Look different when using game tick add instead of animationgetframe

### ISSUE THREAD

**Issue by TommyDong1998** [pixijs/pixi-particles#75]
They should look the same
https://jsfiddle.net/w2hf1856/
https://jsfiddle.net/w2hf1856/1/

**Comment by andrewstart** [comment]
PIXI tickers don't run in milliseconds or seconds, but a target frame delta (delta of 1 = 60 frames per second). The code that Emitters use when connecting to PIXI tickers is `delta / PIXI.settings.TARGET_FPMS / 1000` to get a value in seconds.
