### ISSUE TITLE
Should we use a PrticlesContainer or standard Container?

### ISSUE THREAD

**Issue by Inateno** [pixijs/pixi-particles#77]
Hi there,

Thanks for this useful stuff.

I started using it and it works pretty well but I actually use it in a standard container (no performance problems on my war machine lol) but it's preferable to give a ParticleContainer isn't it?

(I'm talking about this)
http://pixijs.io/examples/#/demos/batch.js

Thanks

**Comment by andrewstart** [comment]
Currently, you should stick to a Container. With PIXI v3 I added support for ParticleContainer that worked pretty well (you gave up the ability to tint particles and had to specially set up your container to allow alpha changes), but the implementation has changed in v4 and it does not work nearly so well. I have not had the time to investigate why yet.

**Comment by Inateno** [comment]
Ok,

I'll stick to standard container, my perfs are ok right now.
If I have any time I'll try to check this on my side too.

But, we should be using ParticlesContainer.
