### ISSUE TITLE
[REQUEST/PR] Gravity simulation

### ISSUE THREAD

**Issue by Inateno** [pixijs/pixi-particles#78]
I would like to make a fountain or something near to that.

I tried with http://pixijs.io/pixi-particles-editor/#sparks but can't find a suitable configuration.

It's not really hard to code inside a PIXI.ParticlesContainer but could be a "nice to have" feature.
I can try to include it in a PR if it's okay for you (I don't want to spend time on a never-included feature ;) ).

**Comment by andrewstart** [comment]
Something like http://pixijs.io/pixi-particles/examples/fountain.html? Set up your particle with a [somewhat low starting speed and a high positive Y acceleration](https://github.com/pixijs/pixi-particles/blob/master/docs/examples/fountain.html#L50).

**Comment by Inateno** [comment]
Yes ! Perfect.

Didn't get it that acceleration was doing this kind of behaviour until now.

Thanks.

**Comment by aditya-ig** [comment]
Thanks @andrewstart, it saved a lot of time!
