### ISSUE TITLE
autoUpdate incorrectly set to true on playOnce and playOnceAndDestroy

### ISSUE THREAD

**Issue by ash-crash** [pixijs/pixi-particles#79]
I would still like to use these methods, but utilise my own update function while doing so. I don't think autoUpdate should be set to true inside these functions. autoUpdate should be specified as true in the constructor configuration argument only

**Comment by userusernamenameception** [comment]
`/**
 * Starts emitting particles, sets autoUpdate to true, and sets up the Emitter to destroy itself
 * when particle emission is complete.
 * @method PIXI.particles.Emitter#playOnceAndDestroy
 * @param {Function} [callback] Callback for when emission is complete (all particles have died off)
 */
p.playOnceAndDestroy = function(callback)
{
	this.autoUpdate = true;
	this.emit = true;
	this._destroyWhenComplete = true;
	this._completeCallback = callback;
};

/**
 * Starts emitting particles, sets autoUpdate to true, and optionally calls a callback
 * when particle emission is complete.
 * @method PIXI.particles.Emitter#playOnce
 * @param {Function} [callback] Callback for when emission is complete (all particles have died off)
 */
p.playOnce = function(callback)
{
	this.autoUpdate = true;
	this.emit = true;
	this._completeCallback = callback;
};`

**Comment by andrewstart** [comment]
autoUpdate is the primary point of these methods. If you wish to tick the emitters yourself, you just need to set `emit = true` to start the emitter.

**Comment by userusernamenameception** [comment]
If I want to use the playOnceAndDestroy and playOnce methods without using the internal particles ticker, (i.e. respect the original choice I made, not to use internal autoUpdate when I instantiated the emitter), then I must manually set autoUpdate to false after calling these methods? Are these methods not designed to work with my own ticker?

**Comment by andrewstart** [comment]
Added in [version 3](https://github.com/pixijs/pixi-particles/releases/tag/3.0.0)
