### ISSUE TITLE
A bug on ring type emitter

### ISSUE THREAD

**Issue by cji3bp62000** [pixijs/pixi-particles#86]
Hey guys!
First thanks to your great effort of making this masterpiece, it helped me a lot on creating fantastic effects.

About the issue of the thread title, I found there is a bug of ring type that, it works same as the circle type. You can check it even in the PixiParticlesEditor.

After Searching code, I found the problem is at **line 906** of pixi-particle.js: 
`if (spawnCircle.minRadius == spawnCircle.radius) {`
`helperPoint.x = Math.random() * (spawnCircle.radius - spawnCircle.minRadius) +`
`spawnCircle.minRadius;`
`}`
I think it should be `spawnCircle.minRadius !== spawnCircle.radius`, to make it work fine as ring.
(at least it worked for me if I plused ! into it)

**Comment by andrewstart** [comment]
Whoops, good catch!

**Comment by davalapar** [comment]
Nice find.
