### ISSUE TITLE
particles.Emitter is not a constructor - TypeScript

### ISSUE THREAD

**Issue by benwager** [pixijs/pixi-particles#87]
I have a typescript Pixi project, I've installed pixi-particles via npm.
I import in to my project using:

`import particles = require("pixi-particles");`

and then try to create an emitter with:

`private emitter:particles.Emitter;`
`this.emitter = new particles.Emitter(...);`

it builds ok, but then gives this error in console

> Uncaught TypeError: particles.Emitter is not a constructor

**Comment by andrewstart** [comment]
I had actually removed Node exports (and forgot to remove the TS info for it) in v3.0.0 because Typescript was giving me trouble when building, but it should be back in v3.1.0 - give that a try.

**Comment by benwager** [comment]
Works a treat. Thanks!
