### ISSUE TITLE
Scale & Alpha tweening ParticleContainer

### ISSUE THREAD

**Issue by digilocker** [pixijs/pixi-particles#88]
Hi, think this may apply to another issue mentioned here, but I've been working on a slot game...

With a score effect I have extended the particlecontainer class which emits a starburst effect when it hits a score.

With the particlecontainer I've noticed that the tweening between the scale and alpha still appears stepped, but with a regular container its a smooth tweened transition.  Is this a known issue & is there any fix for this?  Have also tried using a list for the parameters (preferred method) but the issue remains with either.

Many thanks

**Comment by andrewstart** [comment]
I assume that `scale` and `alpha` or `tint` have been enabled on your particle container? By default `ParticleContainer` only treats `position` as a dynamic property.

**Comment by digilocker** [comment]
> I assume that `scale` and `alpha` or `tint` have been enabled on your particle container? By default `ParticleContainer` only treats `position` as a dynamic property.

My bad, many many thanks!  missed (...arguments) on the constructor so the properties weren't being passed through.  Feel free to mark as closed.
