### ISSUE TITLE
Z-ordering of particles (foreground/background particles)

### ISSUE THREAD

**Issue by Cristy94** [pixijs/pixi-particles#89]
I am using one ParticleContainer for all the particles, is there any way to enforce some z-ordering in the particles? 

I want to have, for example, the smoke ground particles always below the clouds particles, this could be easily done by always adding the ground particles as the first children of the particles array, instead of adding them at the end.

**Comment by Cristy94** [comment]
Oh, I think I can just use the `addAtBack` property.

**Comment by andrewstart** [comment]
Yeah, any ordering fancier than just the `addAtBack` toggle probably needs emitters to add particles to separate containers, because sorting hundreds/thousands of particles probably isn't great.
