### ISSUE TITLE
strange behavior of PropertyList on pixi v4 when used with particle container

### ISSUE THREAD

**Issue by rkdrnf** [pixijs/pixi-particles#90]
When tested with below configuration on pixi v4, alpha, scale and other propertyList configurations are not properly applied to each particle. Expected changes of alpha, scale and other propertyList are applied only at the last few ticks before particle is destroyed. 

```
base configuration: configuration on read me
container: PIXI.particle.ParticleContainer
lifetime: { min = 3, max = 3 }
```

for example, when set scale as below within above setting,
```
scale: {
list: [
    { value: 1, time: 0 },
    { value: 2, time: 1 }
],
isStepped: false
}
```
Particle does not change at all for almost all of its lifetime, but suddenly become big before it disappears.

If I change container as normal PIXI.Container
or lifetime: {min: 0, max: 3}
It seems to works properly.

**Comment by andrewstart** [comment]
You need to [configure your ParticleContainer](http://pixijs.download/release/docs/PIXI.particles.ParticleContainer.html#ParticleContainer) - by default it only updates the position.
